baseURL: https://ahsn-conference-2021.netlify.com/
languageCode: en-us
title: AHSN 2021 Conference Website
theme: vanilla-bootstrap-hugo-theme
googleAnalytics:

taxonomies:
  tag: tags

permalinks:
  post: /:filename/



# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Welcome
    pre: home
    url: /
    weight: 1
  - name: Venue and Travel
    pre: map
    url: /venue/
    weight: 2
  - name: Keynote Speakers
    pre: message-circle
    url: /keynotes/
    weight: 3
  - name: Abstract Submission
    pre: clipboard
    url: /abstract-submission/
    weight: 4
  - name: Registration
    pre: user-plus
    url: /register/
    weight: 5
  - name: Program
    pre: book-open
    url: /conf_program/
    weight: 6
  - name: Contact
    pre: help-circle
    url: /contact/
    weight: 7




params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 1200px
  dateFormat: Jan 2, 2006
  homeText: 
  footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: false
  katex: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2



