baseurl = "/welcome/"
languageCode = "en-us"
title = "AHSN 2021"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

#[[menu.main]]
 #   name = "Welcome"
  #  url = "/welcome/"

[[menu.main]]
    name = "Venue"
    url = "/venue/"

[[menu.main]]
    name = "Keynote Speakers"
    url = "/keynotes/"

[[menu.main]]
    name = "Submit Abstract"
    url = "/abstract-submission/"

[[menu.main]]
    name = "Conference Registration"
    url = "/registration/"

[[menu.main]]
    name = "Conference Program"
    url = "/program/"


[params]
    description = "Website for the 2021 AHSN Conference"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    # Logo is under PUBLIC -- IMAGES
    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"