baseurl = "/"
languageCode = "en-us"
title = "AHSN 2021"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Call for Papers"
    url = "/cfp/"
    #url = "https://github.com/rstudio/blogdown"

[[menu.main]]
    name = "AHSN 2021 Organising Committee"
    url = "/organising-committee/"
    #url = "https://twitter.com/rstudio"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    # Logo is under PUBLIC -- IMAGES
    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"



Testing testing testing!!!!